#!/bin/bash
# Multi-domain setup script for SEO MCP Skills
# Usage: ./setup-multi-domain.sh

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}   SEO MCP Skills - Multi-Domain Setup${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Check if running in Docker
if [ -f /.dockerenv ]; then
    echo -e "${YELLOW}Running inside Docker container${NC}"
    CONFIG_DIR="/app/inputs"
    PROJECTS_DIR="/app"
else
    echo -e "${GREEN}Running on host machine${NC}"
    CONFIG_DIR="$(pwd)/inputs"
    PROJECTS_DIR="$(pwd)"
fi

# Create directories
mkdir -p "$CONFIG_DIR"
mkdir -p "$PROJECTS_DIR"

# Function to create domain config
create_domain() {
    local domain_name=$1
    local domain_url=$2
    local ga4_id=$3
    
    echo -e "${GREEN}Creating config for $domain_name ($domain_url)${NC}"
    
    # Create .env file for domain
    cat > "$CONFIG_DIR/.env.$domain_name" <<EOF
# SEO MCP Skills - $domain_name Configuration
# Generated by setup-multi-domain.sh

# AI Provider (choose at least one)
OPENROUTER_API_KEY=your_openrouter_key
GEMINI_API_KEY=your_gemini_key

# Project Configuration
PROJECT_PATH=/app/project
PROJECT_DOMAIN=$domain_url

# Google Analytics 4
GA4_CREDENTIALS_PATH=/app/inputs/ga4-$domain_name.json
GA4_PROPERTY_ID=$ga4_id

# Google Search Console
GSC_CREDENTIALS_PATH=/app/inputs/gsc-$domain_name.json
GSC_SITE_URL=https://$domain_url/

# Optional: Notifications
TELEGRAM_BOT_TOKEN=your_bot_token
TELEGRAM_CHAT_ID=your_chat_id

# Schedule
SCHEDULE_MONITOR=08:00
SCHEDULE_AUDIT=10:00,22:00
EOF

    echo -e "  ✓ Created $CONFIG_DIR/.env.$domain_name"
    echo -e "  ℹ️  Please add your API keys to this file"
    echo -e "  ℹ️  Place GA4 credentials at $CONFIG_DIR/ga4-$domain_name.json"
    echo -e "  ℹ️  Place GSC credentials at $CONFIG_DIR/gsc-$domain_name.json"
    echo ""
}

# Main setup
echo -e "${YELLOW}How many domains do you want to configure? (1-5)${NC}"
read -r num_domains

if ! [[ "$num_domains" =~ ^[1-5]$ ]]; then
    echo -e "${RED}Invalid number. Using 1 domain.${NC}"
    num_domains=1
fi

for i in $(seq 1 "$num_domains"); do
    echo -e "${YELLOW}Domain $i:${NC}"
    echo -e "  Domain name (e.g., miseguro, clientesite):"
    read -r domain_name
    echo -e "  Full URL (e.g., miseguro.com):"
    read -r domain_url
    echo -e "  GA4 Property ID:"
    read -r ga4_id
    
    create_domain "$domain_name" "$domain_url" "$ga4_id"
done

# Create docker-compose override for these domains
cat > docker-compose.override.yml <<EOF
# Auto-generated by setup-multi-domain.sh
# Run with: docker compose -f docker-compose.yml -f docker-compose.override.yml up -d

version: '3.8'

services:
EOF

for i in $(seq 1 "$num_domains"); do
    # We need to get the domain names from user input again, 
    # but for now create a template
    cat >> docker-compose.override.yml <<EOF
  seo-agent-$i:
    build: .
    container_name: seo-mcp-domain-$i
    volumes:
      - ./inputs/.env.domain$i:/app/.env:ro
      - ./inputs/ga4-domain$i.json:/app/inputs/ga4-credentials.json:ro
      - ./inputs/gsc-domain$i.json:/app/inputs/gsc-credentials.json:ro
      - ./project-domain-$i:/app/project:rw
      - ./outputs-domain-$i:/app/outputs
    environment:
      - TZ=Europe/Madrid
      - PROJECT_DOMAIN=domain$i.com
    restart: unless-stopped
    networks:
      - seo-network

EOF
done

cat >> docker-compose.override.yml <<EOF

networks:
  seo-network:
    driver: bridge
EOF

echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ Setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Next steps:"
echo -e "1. ${YELLOW}Edit${NC} the .env files in $CONFIG_DIR/ with your actual API keys"
echo -e "2. ${YELLOW}Add${NC} your GA4 and GSC JSON credentials to $CONFIG_DIR/"
echo -e "3. ${YELLOW}Mount${NC} your web projects at ./project-domain-X/"
echo -e "4. ${YELLOW}Run${NC}: docker compose -f docker-compose.yml -f docker-compose.override.yml up -d"
echo ""
echo -e "${GREEN}To run a single domain manually:${NC}"
echo -e "  docker compose run --rm seo-mcp-agent monitor"
echo -e "  docker compose run --rm seo-mcp-agent test-openrouter"
echo -e "  docker compose run --rm seo-mcp-agent universal"